name: Run build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build-tensorflow:
    name: Build TensorFlow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tf-version: [2.12, 2.13, 2.14, 2.15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install tensorflow==${{ matrix.tf-version }}
          pip install dist/edge_mdt-0.0.0.dev0-py3-none-any.whl['tf']

      - name: pip list
        run: |
          pip list


  tests-pytorch:
    name: Build PyTorch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install dist/edge_mdt-0.0.0.dev0-py3-none-any.whl['pt']

      - name: pip list
        run: |
          pip list
