name: Run build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build-tensorflow:
    name: Build TensorFlow
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tf-version: [2.12, 2.13, 2.14, 2.15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install jupyterlab tensorflow==${{ matrix.tf-version }}
          pip install dist/edge_mdt-0.0.0.dev0-py3-none-any.whl['tf']

      - name: pip list
        run: |
          pip list

      - name: run notebook
        working-directory: tutorials
        run: |
          jupyter nbconvert --to notebook --execute keras_mobilenetv2.ipynb --output keras_mobilenetv2_output.ipynb
          
      - name: upload output
        working-directory: tutorials
        uses: actions/upload-artifact@v4
        with:
          name: output-tf-${{ matrix.tf-version }}
          path: keras_mobilenetv2_output.ipynb


  tests-pytorch:
    name: Build PyTorch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pt-version: [ '2.0', 2.1, 2.2, 2.3, 2.4, 2.5, 2.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install jupyterlab torch==${{ matrix.pt-version }}
          pip install dist/edge_mdt-0.0.0.dev0-py3-none-any.whl['pt']

      - name: pip list
        run: |
          pip list

      - name: run notebook
        working-directory: tutorials
        run: |
          jupyter nbconvert --to notebook --execute pytorch_mobilenetv2.ipynb --output pytorch_mobilenetv2.ipynb
          

      - name: upload output
        uses: actions/upload-artifact@v4
        working-directory: tutorials
        with:
          name: output-pt-${{ matrix.pt-version }}
          path: pytorch_mobilenetv2.ipynb
