name: Publish

on:
  workflow_dispatch:
    inputs:
      EDGE_MDT_VERSION:
        description: "Version of Edge MDT"
        required: true
      IMX500_CONVERTER_VERSION:
        description: "Version of IMX500 Converter"
        required: true
      MCT_VERSION:
        description: "Version of MCT"
        required: true
      TPC_VERSION:
        description: "version of edge-mdt-tpc"
        required: true
      CUSTOM_LAYERS_VERSION:
        description: "version of edge-mdt-custom-layers"
        required: true

      dry_run:
        description: "Run without publishing (dry run)"
        required: false
        default: true
        type: boolean
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build
        run: |
          EDGE_MDT_VERSION=${{ github.event.inputs.EDGE_MDT_VERSION }} \
          IMX500_CONVERTER_VERSION=${{ github.event.inputs.IMX500_CONVERTER_VERSION }} \
          MCT_VERSION=${{ github.event.inputs.MCT_VERSION }} \
          CUSTOM_LAYERS_VERSION=${{ github.event.inputs.CUSTOM_LAYERS_VERSION }} \
          TPC_VERSION=${{ github.event.inputs.TPC_VERSION }} ./build.sh

      - name: List build artifacts
        run: |
          ls -l dist

      - name: Publish artifacts
        if: ${{ !github.event.inputs.dry_run }}
        run: |
          twine upload dist/*.whl --repository-url ${{ secrets.JFROG_REPO_URL }} \
                -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }}
